/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedStorageRouteImport } from './routes/_authenticated/storage'
import { Route as AuthenticatedSitesRouteImport } from './routes/_authenticated/sites'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedServicesRouteImport } from './routes/_authenticated/services'
import { Route as AuthenticatedSecurityRouteImport } from './routes/_authenticated/security'
import { Route as AuthenticatedPerformanceRouteImport } from './routes/_authenticated/performance'
import { Route as AuthenticatedFoldersRouteImport } from './routes/_authenticated/folders'
import { Route as AuthenticatedDatabasesRouteImport } from './routes/_authenticated/databases'
import { Route as AuthenticatedBackupsRouteImport } from './routes/_authenticated/backups'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedAiCommandRouteImport } from './routes/_authenticated/ai-command'
import { Route as AuthenticatedAgentsRouteImport } from './routes/_authenticated/agents'
import { Route as AuthenticatedSecurityAttemptsRouteImport } from './routes/_authenticated/security.attempts'
import { Route as AuthenticatedSecurityApiKeysRouteImport } from './routes/_authenticated/security.api-keys'
import { Route as AuthenticatedAgentsAgentIdRouteImport } from './routes/_authenticated/agents.$agentId'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStorageRoute = AuthenticatedStorageRouteImport.update({
  id: '/_authenticated/storage',
  path: '/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSitesRoute = AuthenticatedSitesRouteImport.update({
  id: '/_authenticated/sites',
  path: '/sites',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/_authenticated/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedServicesRoute = AuthenticatedServicesRouteImport.update({
  id: '/_authenticated/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSecurityRoute = AuthenticatedSecurityRouteImport.update({
  id: '/_authenticated/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPerformanceRoute =
  AuthenticatedPerformanceRouteImport.update({
    id: '/_authenticated/performance',
    path: '/performance',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedFoldersRoute = AuthenticatedFoldersRouteImport.update({
  id: '/_authenticated/folders',
  path: '/folders',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDatabasesRoute = AuthenticatedDatabasesRouteImport.update({
  id: '/_authenticated/databases',
  path: '/databases',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBackupsRoute = AuthenticatedBackupsRouteImport.update({
  id: '/_authenticated/backups',
  path: '/backups',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/_authenticated/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAiCommandRoute = AuthenticatedAiCommandRouteImport.update({
  id: '/_authenticated/ai-command',
  path: '/ai-command',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAgentsRoute = AuthenticatedAgentsRouteImport.update({
  id: '/_authenticated/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSecurityAttemptsRoute =
  AuthenticatedSecurityAttemptsRouteImport.update({
    id: '/attempts',
    path: '/attempts',
    getParentRoute: () => AuthenticatedSecurityRoute,
  } as any)
const AuthenticatedSecurityApiKeysRoute =
  AuthenticatedSecurityApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedSecurityRoute,
  } as any)
const AuthenticatedAgentsAgentIdRoute =
  AuthenticatedAgentsAgentIdRouteImport.update({
    id: '/$agentId',
    path: '/$agentId',
    getParentRoute: () => AuthenticatedAgentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/agents': typeof AuthenticatedAgentsRouteWithChildren
  '/ai-command': typeof AuthenticatedAiCommandRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/backups': typeof AuthenticatedBackupsRoute
  '/databases': typeof AuthenticatedDatabasesRoute
  '/folders': typeof AuthenticatedFoldersRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/security': typeof AuthenticatedSecurityRouteWithChildren
  '/services': typeof AuthenticatedServicesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sites': typeof AuthenticatedSitesRoute
  '/storage': typeof AuthenticatedStorageRoute
  '/': typeof AuthenticatedIndexRoute
  '/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
  '/security/api-keys': typeof AuthenticatedSecurityApiKeysRoute
  '/security/attempts': typeof AuthenticatedSecurityAttemptsRoute
}
export interface FileRoutesByTo {
  '/agents': typeof AuthenticatedAgentsRouteWithChildren
  '/ai-command': typeof AuthenticatedAiCommandRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/backups': typeof AuthenticatedBackupsRoute
  '/databases': typeof AuthenticatedDatabasesRoute
  '/folders': typeof AuthenticatedFoldersRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/security': typeof AuthenticatedSecurityRouteWithChildren
  '/services': typeof AuthenticatedServicesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sites': typeof AuthenticatedSitesRoute
  '/storage': typeof AuthenticatedStorageRoute
  '/': typeof AuthenticatedIndexRoute
  '/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
  '/security/api-keys': typeof AuthenticatedSecurityApiKeysRoute
  '/security/attempts': typeof AuthenticatedSecurityAttemptsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/agents': typeof AuthenticatedAgentsRouteWithChildren
  '/_authenticated/ai-command': typeof AuthenticatedAiCommandRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/backups': typeof AuthenticatedBackupsRoute
  '/_authenticated/databases': typeof AuthenticatedDatabasesRoute
  '/_authenticated/folders': typeof AuthenticatedFoldersRoute
  '/_authenticated/performance': typeof AuthenticatedPerformanceRoute
  '/_authenticated/security': typeof AuthenticatedSecurityRouteWithChildren
  '/_authenticated/services': typeof AuthenticatedServicesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/sites': typeof AuthenticatedSitesRoute
  '/_authenticated/storage': typeof AuthenticatedStorageRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
  '/_authenticated/security/api-keys': typeof AuthenticatedSecurityApiKeysRoute
  '/_authenticated/security/attempts': typeof AuthenticatedSecurityAttemptsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/agents'
    | '/ai-command'
    | '/audit'
    | '/backups'
    | '/databases'
    | '/folders'
    | '/performance'
    | '/security'
    | '/services'
    | '/settings'
    | '/sites'
    | '/storage'
    | '/'
    | '/agents/$agentId'
    | '/security/api-keys'
    | '/security/attempts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/agents'
    | '/ai-command'
    | '/audit'
    | '/backups'
    | '/databases'
    | '/folders'
    | '/performance'
    | '/security'
    | '/services'
    | '/settings'
    | '/sites'
    | '/storage'
    | '/'
    | '/agents/$agentId'
    | '/security/api-keys'
    | '/security/attempts'
  id:
    | '__root__'
    | '/_authenticated/agents'
    | '/_authenticated/ai-command'
    | '/_authenticated/audit'
    | '/_authenticated/backups'
    | '/_authenticated/databases'
    | '/_authenticated/folders'
    | '/_authenticated/performance'
    | '/_authenticated/security'
    | '/_authenticated/services'
    | '/_authenticated/settings'
    | '/_authenticated/sites'
    | '/_authenticated/storage'
    | '/_authenticated/'
    | '/_authenticated/agents/$agentId'
    | '/_authenticated/security/api-keys'
    | '/_authenticated/security/attempts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedAgentsRoute: typeof AuthenticatedAgentsRouteWithChildren
  AuthenticatedAiCommandRoute: typeof AuthenticatedAiCommandRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedBackupsRoute: typeof AuthenticatedBackupsRoute
  AuthenticatedDatabasesRoute: typeof AuthenticatedDatabasesRoute
  AuthenticatedFoldersRoute: typeof AuthenticatedFoldersRoute
  AuthenticatedPerformanceRoute: typeof AuthenticatedPerformanceRoute
  AuthenticatedSecurityRoute: typeof AuthenticatedSecurityRouteWithChildren
  AuthenticatedServicesRoute: typeof AuthenticatedServicesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSitesRoute: typeof AuthenticatedSitesRoute
  AuthenticatedStorageRoute: typeof AuthenticatedStorageRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/storage': {
      id: '/_authenticated/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof AuthenticatedStorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sites': {
      id: '/_authenticated/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof AuthenticatedSitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/services': {
      id: '/_authenticated/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AuthenticatedServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/security': {
      id: '/_authenticated/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AuthenticatedSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/performance': {
      id: '/_authenticated/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AuthenticatedPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/folders': {
      id: '/_authenticated/folders'
      path: '/folders'
      fullPath: '/folders'
      preLoaderRoute: typeof AuthenticatedFoldersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/databases': {
      id: '/_authenticated/databases'
      path: '/databases'
      fullPath: '/databases'
      preLoaderRoute: typeof AuthenticatedDatabasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/backups': {
      id: '/_authenticated/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof AuthenticatedBackupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ai-command': {
      id: '/_authenticated/ai-command'
      path: '/ai-command'
      fullPath: '/ai-command'
      preLoaderRoute: typeof AuthenticatedAiCommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/agents': {
      id: '/_authenticated/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/security/attempts': {
      id: '/_authenticated/security/attempts'
      path: '/attempts'
      fullPath: '/security/attempts'
      preLoaderRoute: typeof AuthenticatedSecurityAttemptsRouteImport
      parentRoute: typeof AuthenticatedSecurityRoute
    }
    '/_authenticated/security/api-keys': {
      id: '/_authenticated/security/api-keys'
      path: '/api-keys'
      fullPath: '/security/api-keys'
      preLoaderRoute: typeof AuthenticatedSecurityApiKeysRouteImport
      parentRoute: typeof AuthenticatedSecurityRoute
    }
    '/_authenticated/agents/$agentId': {
      id: '/_authenticated/agents/$agentId'
      path: '/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AuthenticatedAgentsAgentIdRouteImport
      parentRoute: typeof AuthenticatedAgentsRoute
    }
  }
}

interface AuthenticatedAgentsRouteChildren {
  AuthenticatedAgentsAgentIdRoute: typeof AuthenticatedAgentsAgentIdRoute
}

const AuthenticatedAgentsRouteChildren: AuthenticatedAgentsRouteChildren = {
  AuthenticatedAgentsAgentIdRoute: AuthenticatedAgentsAgentIdRoute,
}

const AuthenticatedAgentsRouteWithChildren =
  AuthenticatedAgentsRoute._addFileChildren(AuthenticatedAgentsRouteChildren)

interface AuthenticatedSecurityRouteChildren {
  AuthenticatedSecurityApiKeysRoute: typeof AuthenticatedSecurityApiKeysRoute
  AuthenticatedSecurityAttemptsRoute: typeof AuthenticatedSecurityAttemptsRoute
}

const AuthenticatedSecurityRouteChildren: AuthenticatedSecurityRouteChildren = {
  AuthenticatedSecurityApiKeysRoute: AuthenticatedSecurityApiKeysRoute,
  AuthenticatedSecurityAttemptsRoute: AuthenticatedSecurityAttemptsRoute,
}

const AuthenticatedSecurityRouteWithChildren =
  AuthenticatedSecurityRoute._addFileChildren(
    AuthenticatedSecurityRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedAgentsRoute: AuthenticatedAgentsRouteWithChildren,
  AuthenticatedAiCommandRoute: AuthenticatedAiCommandRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedBackupsRoute: AuthenticatedBackupsRoute,
  AuthenticatedDatabasesRoute: AuthenticatedDatabasesRoute,
  AuthenticatedFoldersRoute: AuthenticatedFoldersRoute,
  AuthenticatedPerformanceRoute: AuthenticatedPerformanceRoute,
  AuthenticatedSecurityRoute: AuthenticatedSecurityRouteWithChildren,
  AuthenticatedServicesRoute: AuthenticatedServicesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSitesRoute: AuthenticatedSitesRoute,
  AuthenticatedStorageRoute: AuthenticatedStorageRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
