/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedStorageRouteImport } from './routes/_authenticated/storage'
import { Route as AuthenticatedSitesRouteImport } from './routes/_authenticated/sites'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedServicesRouteImport } from './routes/_authenticated/services'
import { Route as AuthenticatedSecurityRouteImport } from './routes/_authenticated/security'
import { Route as AuthenticatedPerformanceRouteImport } from './routes/_authenticated/performance'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedHubSdkRouteImport } from './routes/_authenticated/hub-sdk'
import { Route as AuthenticatedHubRouteImport } from './routes/_authenticated/hub'
import { Route as AuthenticatedFoldersRouteImport } from './routes/_authenticated/folders'
import { Route as AuthenticatedDatabasesRouteImport } from './routes/_authenticated/databases'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedBackupsRouteImport } from './routes/_authenticated/backups'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedAiCommandRouteImport } from './routes/_authenticated/ai-command'
import { Route as AuthenticatedAgentsRouteImport } from './routes/_authenticated/agents'
import { Route as AuthenticatedAgentLinkRouteImport } from './routes/_authenticated/agent-link'
import { Route as AuthenticatedSecurityAttemptsRouteImport } from './routes/_authenticated/security.attempts'
import { Route as AuthenticatedSecurityApiKeysRouteImport } from './routes/_authenticated/security.api-keys'
import { Route as AuthenticatedAgentsAgentIdRouteImport } from './routes/_authenticated/agents.$agentId'
import { Route as ApiPublicHubIngestRouteImport } from './routes/api/public/hub/ingest'
import { Route as ApiPublicHubHeartbeatRouteImport } from './routes/api/public/hub/heartbeat'
import { Route as ApiPublicHubDispatchRouteImport } from './routes/api/public/hub/dispatch'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStorageRoute = AuthenticatedStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSitesRoute = AuthenticatedSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServicesRoute = AuthenticatedServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSecurityRoute = AuthenticatedSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerformanceRoute =
  AuthenticatedPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHubSdkRoute = AuthenticatedHubSdkRouteImport.update({
  id: '/hub-sdk',
  path: '/hub-sdk',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHubRoute = AuthenticatedHubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFoldersRoute = AuthenticatedFoldersRouteImport.update({
  id: '/folders',
  path: '/folders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDatabasesRoute = AuthenticatedDatabasesRouteImport.update({
  id: '/databases',
  path: '/databases',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBackupsRoute = AuthenticatedBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiCommandRoute = AuthenticatedAiCommandRouteImport.update({
  id: '/ai-command',
  path: '/ai-command',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgentsRoute = AuthenticatedAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgentLinkRoute = AuthenticatedAgentLinkRouteImport.update({
  id: '/agent-link',
  path: '/agent-link',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSecurityAttemptsRoute =
  AuthenticatedSecurityAttemptsRouteImport.update({
    id: '/attempts',
    path: '/attempts',
    getParentRoute: () => AuthenticatedSecurityRoute,
  } as any)
const AuthenticatedSecurityApiKeysRoute =
  AuthenticatedSecurityApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedSecurityRoute,
  } as any)
const AuthenticatedAgentsAgentIdRoute =
  AuthenticatedAgentsAgentIdRouteImport.update({
    id: '/$agentId',
    path: '/$agentId',
    getParentRoute: () => AuthenticatedAgentsRoute,
  } as any)
const ApiPublicHubIngestRoute = ApiPublicHubIngestRouteImport.update({
  id: '/api/public/hub/ingest',
  path: '/api/public/hub/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHubHeartbeatRoute = ApiPublicHubHeartbeatRouteImport.update({
  id: '/api/public/hub/heartbeat',
  path: '/api/public/hub/heartbeat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHubDispatchRoute = ApiPublicHubDispatchRouteImport.update({
  id: '/api/public/hub/dispatch',
  path: '/api/public/hub/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/agent-link': typeof AuthenticatedAgentLinkRoute
  '/agents': typeof AuthenticatedAgentsRouteWithChildren
  '/ai-command': typeof AuthenticatedAiCommandRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/backups': typeof AuthenticatedBackupsRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/databases': typeof AuthenticatedDatabasesRoute
  '/folders': typeof AuthenticatedFoldersRoute
  '/hub': typeof AuthenticatedHubRoute
  '/hub-sdk': typeof AuthenticatedHubSdkRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/security': typeof AuthenticatedSecurityRouteWithChildren
  '/services': typeof AuthenticatedServicesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sites': typeof AuthenticatedSitesRoute
  '/storage': typeof AuthenticatedStorageRoute
  '/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
  '/security/api-keys': typeof AuthenticatedSecurityApiKeysRoute
  '/security/attempts': typeof AuthenticatedSecurityAttemptsRoute
  '/api/public/hub/dispatch': typeof ApiPublicHubDispatchRoute
  '/api/public/hub/heartbeat': typeof ApiPublicHubHeartbeatRoute
  '/api/public/hub/ingest': typeof ApiPublicHubIngestRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/agent-link': typeof AuthenticatedAgentLinkRoute
  '/agents': typeof AuthenticatedAgentsRouteWithChildren
  '/ai-command': typeof AuthenticatedAiCommandRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/backups': typeof AuthenticatedBackupsRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/databases': typeof AuthenticatedDatabasesRoute
  '/folders': typeof AuthenticatedFoldersRoute
  '/hub': typeof AuthenticatedHubRoute
  '/hub-sdk': typeof AuthenticatedHubSdkRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/security': typeof AuthenticatedSecurityRouteWithChildren
  '/services': typeof AuthenticatedServicesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sites': typeof AuthenticatedSitesRoute
  '/storage': typeof AuthenticatedStorageRoute
  '/': typeof AuthenticatedIndexRoute
  '/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
  '/security/api-keys': typeof AuthenticatedSecurityApiKeysRoute
  '/security/attempts': typeof AuthenticatedSecurityAttemptsRoute
  '/api/public/hub/dispatch': typeof ApiPublicHubDispatchRoute
  '/api/public/hub/heartbeat': typeof ApiPublicHubHeartbeatRoute
  '/api/public/hub/ingest': typeof ApiPublicHubIngestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/agent-link': typeof AuthenticatedAgentLinkRoute
  '/_authenticated/agents': typeof AuthenticatedAgentsRouteWithChildren
  '/_authenticated/ai-command': typeof AuthenticatedAiCommandRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/backups': typeof AuthenticatedBackupsRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/databases': typeof AuthenticatedDatabasesRoute
  '/_authenticated/folders': typeof AuthenticatedFoldersRoute
  '/_authenticated/hub': typeof AuthenticatedHubRoute
  '/_authenticated/hub-sdk': typeof AuthenticatedHubSdkRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/performance': typeof AuthenticatedPerformanceRoute
  '/_authenticated/security': typeof AuthenticatedSecurityRouteWithChildren
  '/_authenticated/services': typeof AuthenticatedServicesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/sites': typeof AuthenticatedSitesRoute
  '/_authenticated/storage': typeof AuthenticatedStorageRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
  '/_authenticated/security/api-keys': typeof AuthenticatedSecurityApiKeysRoute
  '/_authenticated/security/attempts': typeof AuthenticatedSecurityAttemptsRoute
  '/api/public/hub/dispatch': typeof ApiPublicHubDispatchRoute
  '/api/public/hub/heartbeat': typeof ApiPublicHubHeartbeatRoute
  '/api/public/hub/ingest': typeof ApiPublicHubIngestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agent-link'
    | '/agents'
    | '/ai-command'
    | '/audit'
    | '/backups'
    | '/clients'
    | '/databases'
    | '/folders'
    | '/hub'
    | '/hub-sdk'
    | '/inbox'
    | '/performance'
    | '/security'
    | '/services'
    | '/settings'
    | '/sites'
    | '/storage'
    | '/agents/$agentId'
    | '/security/api-keys'
    | '/security/attempts'
    | '/api/public/hub/dispatch'
    | '/api/public/hub/heartbeat'
    | '/api/public/hub/ingest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/agent-link'
    | '/agents'
    | '/ai-command'
    | '/audit'
    | '/backups'
    | '/clients'
    | '/databases'
    | '/folders'
    | '/hub'
    | '/hub-sdk'
    | '/inbox'
    | '/performance'
    | '/security'
    | '/services'
    | '/settings'
    | '/sites'
    | '/storage'
    | '/'
    | '/agents/$agentId'
    | '/security/api-keys'
    | '/security/attempts'
    | '/api/public/hub/dispatch'
    | '/api/public/hub/heartbeat'
    | '/api/public/hub/ingest'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/agent-link'
    | '/_authenticated/agents'
    | '/_authenticated/ai-command'
    | '/_authenticated/audit'
    | '/_authenticated/backups'
    | '/_authenticated/clients'
    | '/_authenticated/databases'
    | '/_authenticated/folders'
    | '/_authenticated/hub'
    | '/_authenticated/hub-sdk'
    | '/_authenticated/inbox'
    | '/_authenticated/performance'
    | '/_authenticated/security'
    | '/_authenticated/services'
    | '/_authenticated/settings'
    | '/_authenticated/sites'
    | '/_authenticated/storage'
    | '/_authenticated/'
    | '/_authenticated/agents/$agentId'
    | '/_authenticated/security/api-keys'
    | '/_authenticated/security/attempts'
    | '/api/public/hub/dispatch'
    | '/api/public/hub/heartbeat'
    | '/api/public/hub/ingest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHubDispatchRoute: typeof ApiPublicHubDispatchRoute
  ApiPublicHubHeartbeatRoute: typeof ApiPublicHubHeartbeatRoute
  ApiPublicHubIngestRoute: typeof ApiPublicHubIngestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/storage': {
      id: '/_authenticated/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof AuthenticatedStorageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites': {
      id: '/_authenticated/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof AuthenticatedSitesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/services': {
      id: '/_authenticated/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AuthenticatedServicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/security': {
      id: '/_authenticated/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AuthenticatedSecurityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/performance': {
      id: '/_authenticated/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AuthenticatedPerformanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hub-sdk': {
      id: '/_authenticated/hub-sdk'
      path: '/hub-sdk'
      fullPath: '/hub-sdk'
      preLoaderRoute: typeof AuthenticatedHubSdkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hub': {
      id: '/_authenticated/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof AuthenticatedHubRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/folders': {
      id: '/_authenticated/folders'
      path: '/folders'
      fullPath: '/folders'
      preLoaderRoute: typeof AuthenticatedFoldersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/databases': {
      id: '/_authenticated/databases'
      path: '/databases'
      fullPath: '/databases'
      preLoaderRoute: typeof AuthenticatedDatabasesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/backups': {
      id: '/_authenticated/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof AuthenticatedBackupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-command': {
      id: '/_authenticated/ai-command'
      path: '/ai-command'
      fullPath: '/ai-command'
      preLoaderRoute: typeof AuthenticatedAiCommandRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agents': {
      id: '/_authenticated/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedAgentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agent-link': {
      id: '/_authenticated/agent-link'
      path: '/agent-link'
      fullPath: '/agent-link'
      preLoaderRoute: typeof AuthenticatedAgentLinkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/security/attempts': {
      id: '/_authenticated/security/attempts'
      path: '/attempts'
      fullPath: '/security/attempts'
      preLoaderRoute: typeof AuthenticatedSecurityAttemptsRouteImport
      parentRoute: typeof AuthenticatedSecurityRoute
    }
    '/_authenticated/security/api-keys': {
      id: '/_authenticated/security/api-keys'
      path: '/api-keys'
      fullPath: '/security/api-keys'
      preLoaderRoute: typeof AuthenticatedSecurityApiKeysRouteImport
      parentRoute: typeof AuthenticatedSecurityRoute
    }
    '/_authenticated/agents/$agentId': {
      id: '/_authenticated/agents/$agentId'
      path: '/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AuthenticatedAgentsAgentIdRouteImport
      parentRoute: typeof AuthenticatedAgentsRoute
    }
    '/api/public/hub/ingest': {
      id: '/api/public/hub/ingest'
      path: '/api/public/hub/ingest'
      fullPath: '/api/public/hub/ingest'
      preLoaderRoute: typeof ApiPublicHubIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hub/heartbeat': {
      id: '/api/public/hub/heartbeat'
      path: '/api/public/hub/heartbeat'
      fullPath: '/api/public/hub/heartbeat'
      preLoaderRoute: typeof ApiPublicHubHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hub/dispatch': {
      id: '/api/public/hub/dispatch'
      path: '/api/public/hub/dispatch'
      fullPath: '/api/public/hub/dispatch'
      preLoaderRoute: typeof ApiPublicHubDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAgentsRouteChildren {
  AuthenticatedAgentsAgentIdRoute: typeof AuthenticatedAgentsAgentIdRoute
}

const AuthenticatedAgentsRouteChildren: AuthenticatedAgentsRouteChildren = {
  AuthenticatedAgentsAgentIdRoute: AuthenticatedAgentsAgentIdRoute,
}

const AuthenticatedAgentsRouteWithChildren =
  AuthenticatedAgentsRoute._addFileChildren(AuthenticatedAgentsRouteChildren)

interface AuthenticatedSecurityRouteChildren {
  AuthenticatedSecurityApiKeysRoute: typeof AuthenticatedSecurityApiKeysRoute
  AuthenticatedSecurityAttemptsRoute: typeof AuthenticatedSecurityAttemptsRoute
}

const AuthenticatedSecurityRouteChildren: AuthenticatedSecurityRouteChildren = {
  AuthenticatedSecurityApiKeysRoute: AuthenticatedSecurityApiKeysRoute,
  AuthenticatedSecurityAttemptsRoute: AuthenticatedSecurityAttemptsRoute,
}

const AuthenticatedSecurityRouteWithChildren =
  AuthenticatedSecurityRoute._addFileChildren(
    AuthenticatedSecurityRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgentLinkRoute: typeof AuthenticatedAgentLinkRoute
  AuthenticatedAgentsRoute: typeof AuthenticatedAgentsRouteWithChildren
  AuthenticatedAiCommandRoute: typeof AuthenticatedAiCommandRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedBackupsRoute: typeof AuthenticatedBackupsRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedDatabasesRoute: typeof AuthenticatedDatabasesRoute
  AuthenticatedFoldersRoute: typeof AuthenticatedFoldersRoute
  AuthenticatedHubRoute: typeof AuthenticatedHubRoute
  AuthenticatedHubSdkRoute: typeof AuthenticatedHubSdkRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedPerformanceRoute: typeof AuthenticatedPerformanceRoute
  AuthenticatedSecurityRoute: typeof AuthenticatedSecurityRouteWithChildren
  AuthenticatedServicesRoute: typeof AuthenticatedServicesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSitesRoute: typeof AuthenticatedSitesRoute
  AuthenticatedStorageRoute: typeof AuthenticatedStorageRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgentLinkRoute: AuthenticatedAgentLinkRoute,
  AuthenticatedAgentsRoute: AuthenticatedAgentsRouteWithChildren,
  AuthenticatedAiCommandRoute: AuthenticatedAiCommandRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedBackupsRoute: AuthenticatedBackupsRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedDatabasesRoute: AuthenticatedDatabasesRoute,
  AuthenticatedFoldersRoute: AuthenticatedFoldersRoute,
  AuthenticatedHubRoute: AuthenticatedHubRoute,
  AuthenticatedHubSdkRoute: AuthenticatedHubSdkRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedPerformanceRoute: AuthenticatedPerformanceRoute,
  AuthenticatedSecurityRoute: AuthenticatedSecurityRouteWithChildren,
  AuthenticatedServicesRoute: AuthenticatedServicesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSitesRoute: AuthenticatedSitesRoute,
  AuthenticatedStorageRoute: AuthenticatedStorageRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHubDispatchRoute: ApiPublicHubDispatchRoute,
  ApiPublicHubHeartbeatRoute: ApiPublicHubHeartbeatRoute,
  ApiPublicHubIngestRoute: ApiPublicHubIngestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
